[project]
name = "locust-mcp-server"
version = "0.1.0"
description = "A Model Context Protocol (MCP) server implementation for running Locust load tests."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "locust>=2.33.2",
    "mcp[cli]>=1.6.0",
]
